p5indicatori_user_homepage:
    pattern:  /
    defaults: { _controller: P5indicatoriUserBundle:Default:index }
    
p5indicatori_get_user_trakings_sources:
    pattern:  /sources/{tracking_type}
    defaults: { _controller: P5indicatoriUserBundle:Default:selectedTrackingType, tracking_type: null }
    methods:  [POST]

p5indicatori_save_user_trakings_sources:
    pattern:  /add-user-source
    defaults: { _controller: P5indicatoriUserBundle:Default:addUserSource }

p5indicatori_add_forms_filter:
    pattern: /my-source/{id}
    defaults: { _controller: P5indicatoriUserBundle:FormFilter:addProjectForm, id:null }
    
p5indicatori_get_user_sources:
    pattern: /my-sources
    defaults: { _controller: P5indicatoriUserBundle:Default:userSources }

p5indicatori_get_forms_by_project:
    pattern: /get-forms
    defaults: { _controller: P5indicatoriUserBundle:FormFilter:addFormsByProjectName }

p5indicatori_query_source:
    pattern: /guery-source
    defaults: { _controller: P5indicatoriUserBundle:FormFilter:querySource }