parameters:
#    p5indicatori_user.example.class: P5indicatori\UserBundle\Example

services:
#    p5indicatori_user.example:
#        class: %p5indicatori_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
