parameters:
#    p5indicatori_user.example.class: P5indicatori\UserBundle\Example

services:
#    p5indicatori_user.example:
#        class: %p5indicatori_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    p5indicatori_user.registration.form.type:
        class: P5indicatori\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: p5indicatori_user_registration }