parameters:
#    p5indicatori_user.example.class: P5indicatori\UserBundle\Example

services:
#    p5indicatori_user.example:
#        class: %p5indicatori_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
  p5indicatori_user.registration.form.type:
    class: P5indicatori\UserBundle\Form\Type\RegistrationFormType
    arguments: [%fos_user.model.user.class%]
    tags:
        - { name: form.type, alias: p5indicatori_user_registration }

  p5indicatori_main.menu_builder:
    class: P5indicatori\UserBundle\Menu\MenuBuilder
    arguments: ["@knp_menu.factory"]

  p5indicatori_main.menu.sidebar:
    class: Knp\Menu\MenuItem
    factory_service: p5indicatori_main.menu_builder
    factory_method: createSidebarMenu
    arguments: ["@request"]
    scope: request
    tags:
        - { name: knp_menu.menu, alias: sidebar } # Named "sidebar" this time